server:
  port: 5678

jwt:
  secret-key: XkkTy12

inputfile:
  user-name: classpath:dataset/user.csv
  sensor-name: classpath:dataset/sensorlist.csv


spring:
  application:
    name: relayIotAnalyzer
  datasource:
    url:
  data:
    cassandra:
      keyspace-name: relay
      contact-points: 127.0.0.1
      port: 9042
      schema-action: recreate_drop_unused
      base-package: com.java.relay42.entity
      protocolVersion: V4

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    root: INFO
  file:
    path: logs/
    name: iotanalyzer.log
simulate:
  sensor-data: true
